from groq import Groq
from config import GROQ_API_KEY

def generate_insights(data):
    """
    Generate insights using the Groq API.

    Parameters:
        data (dict): Processed stock data.

    Returns:
        str: Insights generated by the Groq API.
    """
    try:
        # Prepare the prompt
        prompt = (
            "Summarize the following analyst recommendations and company news for NVIDIA (NVDA):\n\n"
            "### Analyst Recommendations:\n"
            f"Strong Buy: {data['recommendations']['strongBuy']:.2f}\n"
            f"Buy: {data['recommendations']['buy']:.2f}\n"
            f"Hold: {data['recommendations']['hold']:.2f}\n"
            f"Sell: {data['recommendations']['sell']:.2f}\n"
            f"Strong Sell: {data['recommendations']['strongSell']:.2f}\n\n"
            "### Company News:\n"
            f"{data['news'] if 'news' in data else 'No news available'}"
        )
        
        # Debug: Print the prompt
        print("Prompt sent to Groq API:")
        print(prompt)
        
        # Generate insights using Groq API
        client = Groq(api_key=GROQ_API_KEY)
        response = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="mixtral-8x7b-32768",  # Use a supported model
            max_tokens=500
        )
        
        # Extract the generated text
        insights = response.choices[0].message.content
        return insights
    except Exception as e:
        print(f"Error generating insights: {e}")
        return None
